---
- name: Converge
  hosts: all
  become: true
  collections:
    - community.general
  vars:
    ufw_enabled: true
    ufw_rules:
      - rule: allow
        port: '8080'
        proto: tcp

  pre_tasks:
    - name: Update apt cache.
      apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'

  roles:
    - weareinteractive.ufw
